name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-20.04                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
      - continue-on-error: true

  artifact:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Hello Github actions" > hello.txt
      - uses: actions/upload-artifact@v3
      - with:
          name: hello 
          path: hello.txt
  prod:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a deploy step"
